### ISSUE TITLE
Training issue, "ModuleNotFoundError: No module named 'confidence_calibrated_adversarial..."

### ISSUE THREAD

**Issue by byunggilljoe** [davidstutz/confidence-calibrated-adversarial-training#1]
Hi, I tried to replicate the experiments from training.

I got an error when I run the following command which is copied from the main readme.md

\<Command\>

`python3 train.py config.svhn confidence_calibrated_adversarial_training_ce_f7p_i40_random_momentum_backtrack_power2_10 set_linf_white`

\<Error\>
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    program.main()
  File "train.py", line 55, in main
    module = importlib.import_module(self.args.config_module)
  File "/home/byunggill/anaconda3/envs/ccat/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named ` 'confidence_calibrated_adversarial_training_ce_f7p_i40_random_momentum_backtrack_power2_10'

I guess the module file 'confidence_calibrated_adversarial_training_ce_f7p_i40_random_momentum_backtrack_power2_10' is omitted from the current commit. Can you give me any hints for this?

\<What-I-have-done list\>
1. Set paths in common/path.py

2. Download data with examples/readme/download_data.py
`python download_dataset.py svhn`

3. Download model with examples/readme/download_model.py and extract the models in BASE_EXPERIMENTS
`python download_model.py svhn ccat`

4. Try to train a model.
`python3 train.py config.svhn confidence_calibrated_adversarial_training_ce_f7p_i40_random_momentum_backtrack_power2_10 set_linf_white`

Thanks in advance!

**Comment by byunggilljoe** [comment]
I finally got it executed by the following command.

`python ./train.py ConfidenceCalibratedAdversarialTrainingInterface config.svhn confidence_calibrated_adversarial_training_ce_f7p_i40_random_momentum_backtrack_power2_10`

Is it a right way to execute the ccat training?

Thanks!

**Comment by byunggilljoe** [comment]
I got a relpy from the author and it is corrected in the main README.
